@startuml

title RemoveBookFromCatalog
actor Client
participant APIGateway
participant Lambda
participant RemoveBookFromCatalogActivity
participant CatalogDao
participant DynamoDBMapper
database DynamoDB

Client -> APIGateway : DELETE /books/:bookId
APIGateway -> Lambda
Lambda -> RemoveBookFromCatalogActivity : execute(request : RemoveBookFromCatalogRequest)
RemoveBookFromCatalogActivity -> CatalogDao : removeBookFromCatalog(bookId : String)
CatalogDao -> DynamoDB : query(CatalogItemVersion.class, bookIdQuery)
DynamoDB -> CatalogDao : List<CatalogItemVersion> results.get(0)
alt if book == null || book.isInactive()
    CatalogDao -> Lambda : throw BookNotFoundException
    Lambda -> APIGateway
    APIGateway -> Client : 404 Response
end
CatalogDao -> DynamoDB : save(book) set book to inactive
DynamoDB -> CatalogDao : void
CatalogDao -> RemoveBookFromCatalogActivity : true
RemoveBookFromCatalogActivity -> Lambda : RemoveBookFromCatalogResponse true
Lambda -> APIGateway
APIGateway -> Client : Book Deleted

@enduml